/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcanpoll;

import javax.swing.JOptionPane;

/**
 *
 * @author deh
 */
public class NewJFrame extends javax.swing.JFrame {
    public Canmsginfo cmi1; // Xmit (radio button 1)
    public static Canmsginfo cmi2; // Rcv (radio button 2)
    public Canmsg2j cmsg;
    public int seqsend;
    private Integer radio;
    private long payloadlong; // can hold 8 bytes of payload
    
    public static Long canidrcv;
    public static int canidrcvi;
    public static int canmsgct;
    
    /**
     * Creates new form NewJFrame
     * @param cib
     */
    public NewJFrame() {
        initComponents();
        Canmsginfo c1 = new Canmsginfo(); cmi1 = c1;
        Canmsginfo c2 = new Canmsginfo(); cmi2 = c2;
        Canmsg2j m = new Canmsg2j(); cmsg = m;
        seqsend = 0; radio = 0;payloadlong = 0;
        radio = 1;
        canidrcv = 0x0000E1E00000L; // Test CAN ID
        canidrcvi = canidrcv.intValue();
        canmsgct = 0;   // Count received CAN msgs
   }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pccPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("pccPU").createEntityManager();
        canidQuery = java.beans.Beans.isDesignTime() ? null : pccPUEntityManager.createQuery("SELECT c FROM Canid c");
        canidList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : canidQuery.getResultList();
        canidQuery3 = java.beans.Beans.isDesignTime() ? null : pccPUEntityManager.createQuery("SELECT c FROM Canid c");
        canidList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : canidQuery3.getResultList();
        canidQuery1 = java.beans.Beans.isDesignTime() ? null : pccPUEntityManager.createQuery("SELECT c FROM Canid c");
        canidList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : canidQuery1.getResultList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        canidQuery2 = java.beans.Beans.isDesignTime() ? null : pccPUEntityManager.createQuery("SELECT c FROM Canid c");
        canidList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : canidQuery2.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, canidList2, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${canidName}"));
        columnBinding.setColumnName("Canid Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${canidHex}"));
        columnBinding.setColumnName("Canid Hex");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${canMsgFmt}"));
        columnBinding.setColumnName("Can Msg Fmt");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(jTable1);
        jRadioButton1.setSelected(true);

        jButton1.setText("Send");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Xmit  ->");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jTextField2.setText("0");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField2MouseExited(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("0");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField3MouseExited(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("0");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField4MouseExited(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setText("0");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField5MouseExited(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel2.setText("DLC");

        jLabel3.setText("[0]");

        jLabel4.setText("DLC");

        jLabel5.setText("[0]-[dlc-1]");

        jTextField6.setText("0");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField6MouseExited(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Dec|Hex");

        jLabel8.setText("Dec");

        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField7MouseExited(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel10.setText("Description");

        jTextField8.setText("0");
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField8MouseExited(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setText("0");
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField9MouseExited(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel11.setText("[0]");

        jLabel12.setText("[1]-[7]");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Xmit select");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Receive Select");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jTextField10.setText("0");
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField10MouseExited(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel13.setText("[0]-[7]");

        jLabel14.setText("Dec|Hex|Float");

        jLabel15.setText("Dec|Hex|Float");

        jLabel16.setText("Dec|Hex");

        jTextField12.setText("0");

        jTextField15.setText("UNDEF");
        jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField15MouseExited(evt);
            }
        });
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel20.setText("Msg Fmt");

        jTextField16.setText("0");

        jLabel18.setText("Msg counter");

        jLabel21.setText("CAN ID");

        jLabel22.setText("CAN NAME");

        jLabel23.setText("Fomatted Reply");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(23, 23, 23)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(280, 280, 280)
                                    .addComponent(jLabel22)
                                    .addGap(30, 30, 30))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton1)
                                    .addGap(41, 41, 41)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jTextField9)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addComponent(jLabel14))
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(80, 80, 80))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))))
                                .addGap(4, 4, 4)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int Col = jTable1.getSelectedColumn();  // Selected Col (0 - n)
        int Row = jTable1.getSelectedRow();     // Selected Row (0 - n)
        if (radio == 1){
            setjTableSelection(cmi1);
            jTextField2.setText(jTable1.getValueAt(Row, 1).toString());// can_hex
            jTextField1.setText(jTable1.getValueAt(Row, 0).toString());// can_name
            jTextField7.setText(jTable1.getValueAt(Row, 3).toString());// description
        }else{ // Here, radio button 2 active (receive selections)
            setjTableSelection(cmi2);
            jTextField12.setText(jTable1.getValueAt(Row, 1).toString());
            jTextField13.setText(jTable1.getValueAt(Row, 0).toString());
            jTextField14.setText(jTable1.getValueAt(Row, 3).toString());
            String ss = jTable1.getValueAt(Row, 2).toString(); // msg_fmt
            jTextField15.setText(ss);
            // Remember sign extends and will screw up table lookup
            long l1 = Integer.parseUnsignedInt(jTable1.getValueAt(Row, 1).toString(), 16);
            l1 = (l1 << 32) >>> 32; // Get rid of upper bits
            canidrcv = l1;           // Needed for comparisons in binary search
            canidrcvi = canidrcv.intValue();
            cmi2.pay_type_code = Jcanpoll.lookUp(canidrcv);// name -> numeric code
        }
        zeroRcvFields();
    }//GEN-LAST:event_jTable1MouseClicked

    private void setjTableSelection(Canmsginfo cmi){
        int Col = jTable1.getSelectedColumn();  // Selected Col (0 - n)
        int Row = jTable1.getSelectedRow();     // Selected Row (0 - n)
        
        // Testing
        System.out.format("CLIC Col ct: %d Col: %d Row: %d\n",jTable1.getColumnCount(),jTable1.getSelectedColumn(),jTable1.getSelectedRow());
        String s = jTable1.getValueAt(Row, Col).toString();
        System.out.format("Radio: %d Selected: %s\n",radio,s);
        
        /* Extract and Copy row-col selection */
        cmi.can_name = jTable1.getValueAt(Row, 0).toString();
        long ltmp = Long.parseLong(jTable1.getValueAt(Row, 1).toString(), 16);
        ltmp = (ltmp << 32) >>>32;  // Sign extension fix needed for comparisons
        cmi.can_hex = ltmp;
        cmi.descript_canid = jTable1.getValueAt(Row, 2).toString();
        cmi.can_msg_fmt = jTable1.getValueAt(Row, 3).toString();
        System.out.format("cmi: %s\t0x%08X %s\t%s\n",cmi.can_name,cmi.can_hex,cmi.descript_canid,cmi.can_msg_fmt);
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Do final msg preparation then send message
        System.out.format("cmi1: %s\t0x%08X %s\t%s\n",cmi1.can_name,cmi1.can_hex,cmi1.descript_canid,cmi1.can_msg_fmt);
System.out.format("can_hex: %08X dlc: %d\n", cmi1.can_hex.intValue(),cmsg.dlc);
        cmsg.pb[0] = (byte)(seqsend & 0xff); // Sequence number
        seqsend += 1;
        cmsg.id = cmi1.can_hex.intValue(); // CAN ID
//cmsg.dlc = Integer.parseInt(jTextField3.getText()); // Payload length
System.out.format("###cmsg.dlc: %d\n",cmsg.dlc);
        cmsg.out_1longvar(payloadlong,cmsg.dlc); // Setup msg byte array from long
        String s = cmsg.out_prep(); // Final prep: add checksum and build string
        System.out.format("Send: %s\n",s);
        MessagePipeline pipe = MessagePipeline.getInstance();
        pipe.WriteToSocket(s);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        System.out.format("jTextField1MouseClicked: Description field\n");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
 System.out.println("jTextField3ActionPerformed");
     textField3cnvt();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
System.out.println("jTextField4ActionPerformed");        
    textField4cnv();
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
 System.out.println("jTextField5ActionPerformed");
//        textField5cnv();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
System.out.println("jTextField6ActionPerformed");
  //      textField6cnv();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
System.out.println("jTextField2ActionPerformed");
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
       System.out.format("jTextField1MouseClicked: %s\n",jTextField2.getText());
       cmi1.can_hex = Long.parseLong(jTextField2.getText(), 16);
       System.out.format("jTextField1MouseClicked: %08X\n",cmi1.can_hex);
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
 System.out.format("jTextField9ActionPerformed\n");
         textFile9cnv();
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        radio = 1;
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        radio = 2;
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
    // Mistake made adding this.  Just leave it.
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
System.out.println("jTextField10ActionPerformed");
        textField10cnv();
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
System.out.println("jTextField8ActionPerformed");
        textField8cnv();
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseExited
System.out.println("jTextField3MouseExited");
        textField3cnvt();
    }//GEN-LAST:event_jTextField3MouseExited

    private void jTextField4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseExited
System.out.println("jTextField4MouseExited");
        textField4cnv();
    }//GEN-LAST:event_jTextField4MouseExited

    private void jTextField5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseExited
 System.out.println("jTextField5MouseExited");
        textField5cnv();
    }//GEN-LAST:event_jTextField5MouseExited

    private void jTextField8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseExited
 System.out.println("jTextField8MouseExited");
        textField8cnv();
    }//GEN-LAST:event_jTextField8MouseExited

    private void jTextField9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseExited
 System.out.println("jTextField9MouseExited");
        textFile9cnv();
    }//GEN-LAST:event_jTextField9MouseExited

    private void jTextField10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseExited
System.out.println("jTextField10MouseExited");
        textField10cnv();
    }//GEN-LAST:event_jTextField10MouseExited

    private void jTextField2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseExited
System.out.println("jTextField2MouseExited");
//        cmi1.can_hex = Long.parseLong(jTextField2.getText(), 16);
        cmi1.can_hex = parseLongChkHex(jTextField2.getText());
        
       System.out.format("jTextField1MouseClicked: %08X\n",cmi1.can_hex);
    }//GEN-LAST:event_jTextField2MouseExited

    private void jTextField6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseExited
System.out.println("jTextField6MouseExited");
        //textField6cnv();
    }//GEN-LAST:event_jTextField6MouseExited

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        setTypeCode();
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField15MouseExited
        setTypeCode();
    }//GEN-LAST:event_jTextField15MouseExited

    private void jTextField7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseExited
System.out.println("jTextField7MouseExited");
    }//GEN-LAST:event_jTextField7MouseExited

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
System.out.println("jTextField7ActionPerformed");
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void zeroRcvFields(){
        jTextField5.setText("0");
        jTextField6.setText("0");
        jTextField11.setText("0");
        jTextField16.setText("0");
        canmsgct = 0;   // Count received CAN msgs
    }
    
    public void setTypeCode(){
//cmi2.pay_type_code = 24; // ## Test/Debug ##
// TODO lookup Type Code given Type_Name
    }

    public static void setText11(String s1, String s2, String s3){
        canmsgct += 1;
        String sct = String.format("%d",canmsgct);
        jTextField16.setText(sct); // Display 
        jTextField11.setText(s1);
        jTextField5.setText(s2);
        jTextField6.setText(s3);
    }
   private Integer parseIntChk(String s){
        Integer i;
        try{
            i = Integer.parseInt(s);
        }catch (NumberFormatException e){
            System.out.println("Parse Int failed\n");
            JOptionPane.showMessageDialog(null, e.toString(), "Not Decimal",
                                    JOptionPane.ERROR_MESSAGE);
            i = 0;
        }
        return i;
    }
      private long parseLongChkDec(String s){
        long i;
        try{
            i = Long.parseLong(s);
        }catch (NumberFormatException e){
            System.out.println("Parse long failed\n");
            JOptionPane.showMessageDialog(null, e.toString(), "Not Decimal",
                                    JOptionPane.ERROR_MESSAGE);
            i = 0;
        }
        return i;
    }
    private long parseLongChkHex(String s){
        long i;
        try{
            i = Long.parseLong(s, 16);
        }catch (NumberFormatException e){
            System.out.println("Parse Int failed\n");
            JOptionPane.showMessageDialog(null, e.toString(), "Not H",
                                    JOptionPane.ERROR_MESSAGE);
            i = 0;
        }
        return i;
    }
    private long payloadParse(String s){
        long i;
        int k = s.indexOf("0x");
        if (k < 0){
            i = parseLongChkDec(s);
        }else{
            i = parseLongChkHex(s.substring(k+2));
        }
        return i;
    }
    
    private int payloadParseType(String s){
        long i;
        if (s.contains("0x")){
            return 1;   // Hex = 1
        }
        if (s.contains(".")){
            return 2;   // Assume float
        }
        return 0;
    }
/** Convert String typed into a TextField that is assumed to be
 * Dec, Hex (0x prefix), float.  The float is converted to the
 * raw bits.
 * @param args String 
 * @return long 
 *   with raw bits
*/ 
    private long fieldCnvt(String s){
 
        int sw = payloadParseType(s);
        long i = 0; 
        switch(sw){
            case 0: // Appears to be decimal
            case 1: // Appears to be hex
                i = payloadParse(s);
                break;
            case 2: // Appears to be float
                Float f = Float.parseFloat(s);
                i = Float.floatToRawIntBits(f);                
                break;                
        }
        return i;
    }
    
    private void textField3cnvt(){
        //cmsg.dlc = Integer.parseInt(jTextField3.getText());
        cmsg.dlc = parseIntChk(jTextField3.getText());
        if (cmsg.dlc > 8) cmsg.dlc = 8;     // Limit payload size
        jTextField3.setText(Integer.toString(cmsg.dlc));
        System.out.format("DLC entered %d\n",cmsg.dlc );
    }
    private void textField4cnv(){
        String s = jTextField4.getText();
        System.out.format("[0] str: %s\n",s);
        long l = payloadParse(s) & 0xff;
        payloadlong = (payloadlong & ~0xff) | l; // Mask old data or new
        System.out.format("[0]: %d %X\n",payloadlong,payloadlong);
        jTextField8.setText(s); // Duplicate other [0] field
    }
    private void textField5cnv(){
        String s = jTextField5.getText();
        System.out.format("[0] str: %s\n",s);
        long l = payloadParse(s) & 0xff;
        payloadlong = (payloadlong & ~0xff00) | (l << 8); // Mask old data or new
        System.out.format("[0]: %d %X\n",payloadlong,payloadlong);
    }
        private void textField6cnv(){
        String s = jTextField6.getText();
        long l = fieldCnvt(s);   // Convert dec,hex,or float to raw bits
        long l2 = -1; l2 = ((l2 >> 16) << 16); // Construct 0xff...ff0000
        payloadlong = (payloadlong & ~l2) | (l << 16); // Mask old data or new
System.out.format("Hex: %08X Dec: %d input: %s\n",payloadlong,payloadlong,s);
    }
    private void textField8cnv(){
        String s = jTextField8.getText();
        long l = payloadParse(s) & 0xff;
        payloadlong = (payloadlong & ~0xff) | l; // Mask old data or new
        System.out.format("[0]: %d %X\n",payloadlong,payloadlong); 
        jTextField4.setText(s); // Duplicate other [0] field
    }
    private void textFile9cnv(){
        String s = jTextField9.getText();
        long l = fieldCnvt(s);   // Convert dec,hex,or float to raw bits
        long l2 = -1; l2 = ((l2 >> 8) << 8); // Construct 0xff...ff0000
        payloadlong = (payloadlong & ~l2) | (l << 8); // Mask old data or new
System.out.format("Hex: %08X Dec: %d input: %s\n",payloadlong,payloadlong,s);
    }
    private void textField10cnv(){
        String s = jTextField10.getText();
        payloadlong = fieldCnvt(s);   // Convert dec,hex,or float to raw bits
System.out.format("Hex: %08X Dec: %d input: %s\n",payloadlong,payloadlong,s); 
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private java.util.List<jcanpoll.Canid> canidList;
    private java.util.List<jcanpoll.Canid> canidList1;
    private java.util.List<jcanpoll.Canid> canidList2;
    private java.util.List<jcanpoll.Canid> canidList3;
    private javax.persistence.Query canidQuery;
    private javax.persistence.Query canidQuery1;
    private javax.persistence.Query canidQuery2;
    private javax.persistence.Query canidQuery3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private static javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private static javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private static javax.swing.JTextField jTextField5;
    private static javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.persistence.EntityManager pccPUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
